### ISSUE TITLE
Documentation link in the README goes to a 404

### ISSUE THREAD

**Issue by markstory** [wsssoftware/cakephp-datatables#1]
**Describe the bug**

The 'documentation' link in the README goes to an invalid URL. It would be good if the link worked or wasn't there at all.

**Comment by allanmcarvalho** [comment]
Yeah, I changed the documentation type... Now I am using sphinx with cakephp theme. You can see on https://cakephp-datatables.readthedocs.io/en/latest/intro/
It's in beginig.
